Fix signal handling for the batch consumer
php-amqplib/RabbitMqBundle pull request #504
Opened 2017-12-07 12:01 UTC by 1ed

Based on #430

2021-03-16 12:24 UTC, mihaileu commented
@andreea-anamaria could you please take a look.

2021-03-18 08:53 UTC, andreea-anamaria approved these changes

2021-03-18 09:06 UTC, andreea-anamaria requested changes
Please update the branch from master.

2021-03-18 09:07 UTC, mihaileu commented
already present in master

2021-03-18 09:07 UTC, closed without merging