Dispatch events around publishing
php-amqplib/RabbitMqBundle pull request #598
Opened 2019-09-18 16:36 UTC by smatyas

Hi, I saw similar requests in #147 and #201 and I wanted this feature to collect more metrics in my application.

Would you consider merging a PR like this?

Of course, we can work more on the details like event names, places etc., I'd just like to know an early answer if it's a no-go.

2019-09-30 10:40 UTC, smatyas commented
@videlalvaro is this something you would consider merging?

2021-03-16 11:31 UTC, mihaileu commented
@theodormanolescu what do you think about this ?

2021-03-16 12:22 UTC, theodormanolescu requested changes

2021-03-16 12:22 UTC, theodormanolescu commented on RabbitMq/Producer.php
> +        $this->dispatchEvent(BeforePublishingMessageEvent::NAME, new BeforePublishingMessageEvent($this, $msg));
Please keep in mind that the signature of the EventDispatcherInterface::dispatch() method has been changed to dispatch($event, string $eventName = null): object since 5.0.0

2024-10-17 18:45 UTC, mihaileu commented
released in #728

2024-10-17 18:45 UTC, closed without merging