Group consumer
php-amqplib/RabbitMqBundle pull request #631
Opened 2021-03-28 17:40 UTC by sashaaro

Consume multiple queues by one worker command for reduce complexity and simplify debugging.
A lot of running php commands can consume significant memory size and would be not convinient in development and testing environment which no need parallel executation.

2021-04-16 14:44 UTC, pedro-stanaka requested changes
Here are my 2¢. In general, I think you should add some tests to cover the new code and fix some PHPDocs and typos/wording on the README file. I am looking forward on testing this on my end.

2021-04-16 14:44 UTC, pedro-stanaka commented on RabbitMq/GroupConsumer.php
> +            $consumer->setChannel($this->ch);
In general, we should cover this class with tests. I think this here is quite important behavior, we should add assertions for it.

2021-04-16 14:44 UTC, pedro-stanaka commented on RabbitMq/GroupConsumer.php
> +
I would add here:

```php
/**
 * iterable<BaseConsumer>
 */
```

2021-05-19 14:31 UTC, sashaaro commented
@pedro-stanaka I have not time to finish it. Welcome to contribute it.

2021-08-31 20:22 UTC, closed without merging