Issue #660
php-amqplib/RabbitMqBundle pull request #662
Opened 2021-10-05 12:45 UTC by amigian74

Use confirmation acknowledgment for producer

2021-11-04 08:03 UTC, Eloar requested changes
Your test fails, you should review it

2021-11-04 08:03 UTC, Eloar commented on RabbitMq/Producer.php
> +    public function publish($msgBody, $routingKey = '', $additionalProperties = array(), array $headers = null)
why would you change routing key from `null` to `''`?

2021-11-30 12:50 UTC, ruudk commented
can you please give this a proper title?

2021-11-30 12:56 UTC, amigian74 commented on RabbitMq/Producer.php
> +    public function publish($msgBody, $routingKey = '', $additionalProperties = array(), array $headers = null): bool
These changes are not from me - I only changed the return type for the function publish

2021-11-30 12:56 UTC, amigian74 commented on RabbitMq/Producer.php
> +    public function publish($msgBody, $routingKey = '', $additionalProperties = array(), array $headers = null)
These changes are not from me - I only changed the return type for the function publish

2022-01-03 07:09 UTC, amigian74 commented
Happy new year. What is missing here?

2022-01-03 07:59 UTC, Eloar commented
@amigian74 as far as I can tell there was requested change to ProducerInterface (to not to declare return type with type hint as it is breaking change). I was suggesting adding description to doc comment of added method.

2022-01-11 12:58 UTC, amigian74 commented
Hi. In my opinion all requests should by fullfilled by now

2022-01-28 13:07 UTC, amigian74 commented
How ist this possible? I only added a doc comment to the new function.

2022-03-17 09:59 UTC, amigian74 commented
Can anybody please help me with this - this feature is really important for us

2022-06-23 05:56 UTC, amigian74 commented
Is there still something to do here?

2022-08-30 09:09 UTC, amigian74 commented
Hi, are you planning a new release soon with this request in it? It's really important for me,

2022-12-12 16:31 UTC, closed without merging