Symfony 5.4 deprecations adressed
php-amqplib/RabbitMqBundle pull request #679
Opened 2021-12-17 07:37 UTC by Eloar

Noticed some deprecation messages from RabbitMqBundle when upgraded my project from Symfony 5.3 to Symfony 5.4. Added some more type hinting in Extension class.

2021-12-17 13:09 UTC, mihaileu commented
@Eloar  is it working with older sy versions ?

2021-12-17 13:12 UTC, Eloar commented
@mihaileu based on tests/checks it does work with lowest version currently supported (Symfony 4.3).

2021-12-17 13:17 UTC, mihaileu commented
I think we can merge it after merge this one: https://github.com/php-amqplib/RabbitMqBundle/pull/675 as we will lose that older sy compatibility

2021-12-17 13:18 UTC, mihaileu commented on DependencyInjection/Configuration.php
> +    public function getConfigTreeBuilder() : TreeBuilder
if there is a space between ) and : we should eliminate it and stick to the PSR12

2021-12-17 14:45 UTC, Eloar commented on DependencyInjection/Configuration.php
> +    public function getConfigTreeBuilder() : TreeBuilder
thx for pointing that out. changed all the places I made that mistake and updated commit. It is now ready to be merged if no other issues appear.

2021-12-21 13:12 UTC, javer requested changes

2021-12-21 13:12 UTC, javer commented on phpunit.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Why is this file committed when there is the identical one in https://github.com/php-amqplib/RabbitMqBundle/blob/master/phpunit.xml.dist ?

2021-12-21 13:12 UTC, javer commented on DependencyInjection/OldSoundRabbitMqExtension.php
> +    public function getConfiguration(array $config, ContainerBuilder $container): ?ConfigurationInterface
It's unlikely that this method will return null ever.

2021-12-21 13:12 UTC, mihaileu commented on DependencyInjection/OldSoundRabbitMqExtension.php
> +    public function getConfiguration(array $config, ContainerBuilder $container): ?ConfigurationInterface
deleted

2021-12-21 13:13 UTC, mihaileu approved these changes

2021-12-21 13:13 UTC, merged